### ISSUE TITLE
First build

### ISSUE THREAD

**Issue by persianpros** [PLi-metas/meta-hypercube#1]
Hi my friend,

Would you please help me with compiling an image for su980? It uses old kernel which I know you know it better than me 👍 

I had this model years before on https://github.com/OpenHyperCube

**Comment by Hains** [comment]
OK. But not within a few days. I'm very busy now at the moment.
Only small and easy things for now.
But i start with it as soon as possible.

**Comment by persianpros** [comment]
Thanks a lot my friend, build is ok now 👍 💯
