### ISSUE TITLE
Hola buenas

### ISSUE THREAD

**Issue by trunca** [PLi-metas/meta-hypercube#2]
gracias por el tiempo gastado con la creación del meta-hypercube
e compilado el meta pero no arranca el su980 entra en bucle 
creo que no crea bien el kernel
un saludo y gracias

**Comment by Hains** [comment]
Hi

Hm.not much information.
Do you get:
-splashscreen?
-Enigma2 bootlogo?

Can you;
-telnet to box?
-FTP to box?

Do you have crashlogs? dsmeg's ?
What's the status of display, led(s) etc?

Unfortunately we don't own the box ourself.
But perhaps with more information we can help you.

**Comment by trunca** [comment]
Hola gracias por el interés, yo tengo hypercube

  Can you;
-telnet to box? NO
-FTP to box? NO

no llega a cargar entra en bucle
en el display sale enigma2 y empieza la cuenta atras de 5,4,3,2,1 vuelve a comenzar

si cambio el kernel por el de openpli4 comienza la carga y la puedo conectar por telnet 
me da un monton de fallos de enigma2 por que el kernel no esta con los cambios del  enigma2 nuevo

ahora estoy un poco liado con el trabajo pero ya seguiré haciendo pruebas y se las comento

si hace falta que haga alguna prueba dímelo. en cuanto tenga un rato hago las pruebas

un saludo

**Comment by vuteam** [comment]
hello sir trunca

please what enigma2 source used for build image for su980???
